CREATE TABLE Projects (
	projectid SERIAL PRIMARY KEY,
	requestorname varchar(255),
	teammailer varchar(255),
	othercontacts text,
	businessunit varchar(255),
	nickname varchar(255),
	activity text,
	department varchar(255),
	requestdate date,
	deliverydate date,
	projectname varchar(255),
	projectscope text,
	buinessimpact text,
	otherinfo text,
	accesstype varchar(255),
	circuitsize varchar(255),
	diversity boolean,
	protection boolean,
	intercampus boolean,
	latency varchar(255),
	dependencies text,
	requirementsurl varchar(255),
	documentation varchar(255),
	buildingid_A varchar(255),
	company_A varchar(255),
	street_A varchar(255),
	city_A varchar(255),
	state_A varchar(255),
	zipcode_A varchar(255),
	tel_A varchar(255),
	floor_A varchar(255),
	contactname_A varchar(255),
	conctacttitle_A varchar(255),
	contactcompany_A varchar(255),
	contactemail_A varchar(255),
	contactnumber_A varchar(255),
	cellnumber_A varchar(255),
	buildingid_B varchar(255),
	company_B varchar(255),
	street_B varchar(255),
	city_B varchar(255),
	state_B varchar(255),
	zipcode_B varchar(255),
	tel_B varchar(255),
	floor_B varchar(255),
	contactname_B varchar(255),
	conctacttitle_B varchar(255),
	contactcompany_B varchar(255),
	contactemail_B varchar(255),
	contactnumber_B varchar(255),
	cellnumber_B varchar(255));

CREATE TABLE Assignees (
	assigneeid SERIAL PRIMARY KEY,
	function text,
	name text);